include_guard(GLOBAL)

function(aila_select_runtime_dlls)
    cmake_parse_arguments(PARSE_ARGV 0 AILA_SELECT "" "OUTPUT_FILES" "DIRECTORIES")
    if(NOT AILA_SELECT_OUTPUT_FILES)
        message(FATAL_ERROR "aila_select_runtime_dlls requires OUTPUT_FILES.")
    endif()

    set(selected_files)
    set(selected_keys)
    foreach(runtime_dir IN LISTS AILA_SELECT_DIRECTORIES)
        if(NOT IS_DIRECTORY "${runtime_dir}")
            continue()
        endif()

        file(GLOB runtime_files LIST_DIRECTORIES FALSE "${runtime_dir}/*.dll")
        list(SORT runtime_files CASE INSENSITIVE)
        foreach(runtime_file IN LISTS runtime_files)
            get_filename_component(runtime_name "${runtime_file}" NAME)
            string(TOLOWER "${runtime_name}" runtime_key)
            list(FIND selected_keys "${runtime_key}" selected_index)
            if(selected_index EQUAL -1)
                list(APPEND selected_keys "${runtime_key}")
                list(APPEND selected_files "${runtime_file}")
            endif()
        endforeach()
    endforeach()

    set(${AILA_SELECT_OUTPUT_FILES} "${selected_files}" PARENT_SCOPE)
endfunction()
